✨ keybinds
mlexchange/mlex_highres_segmentation pull request #43
Opened 2023-07-14 11:15 UTC by danton267

2023-07-21 21:30 UTC, hannahker commented on components/control_bar.py
> +                logging=True,
Probably want to turn this off since it's just useful for dev

2023-07-28 14:39 UTC, hannahker commented
Feel free to merge once merge conflicts have been resolved.

2023-08-03 16:10 UTC, danton267 commented
- [ ] allow key binds when the sidebar is closed
- [ ] add notification on color change
  - [ ] add class name into notification

2023-08-10 19:40 UTC, tamidodo commented
There's an extra line for the line annotation mode at the end of the annotation keybind instructions and a typo: "Keybding Shortcuts" instead of "Keybinding Shortcuts" 
<img width="241" alt="Screenshot 2023-08-10 at 12 38 28 PM" src="https://github.com/mlexchange/mlex_highres_segmentation/assets/61042740/a3b1a00a-851b-439e-825b-456e12cd3c60">

2023-08-11 00:05 UTC, MinaMirz requested changes
shift+[1-9] doesn't seem to work on Safari. Everything else was functional.

2023-08-11 12:53 UTC, MinaMirz approved these changes

2023-08-11 12:56 UTC, danton267 commented
Had to remove alt keys/shift/ctrl because of issues with browser support and cross-compatibility between OS

- ctrl is shared between win and mac but on windows browsers ctrl+1 changes to the first tab of the browser
- alt/option is not shared
- holding shift changes 123456789 to !"£$%^&*( 

if this is requested in the future, we can ask for the browser header to determine what OS/browser user is using and tell app to listen/react to different keys

2023-08-11 12:56 UTC, merged